// Generated by scripts/generate-market-pages.mjs. Do not edit by hand;
// edit scripts/seo-content/markets.mjs and re-run the generator.
window.REQUITY_MARKETS = [
  {
    "slug": "dallas",
    "name": "Dallas",
    "stateCode": "TX",
    "statewide": false,
    "lat": 32.7767,
    "lng": -96.797,
    "radiusMiles": 75,
    "url": "/dallas-real-estate-agent.html"
  },
  {
    "slug": "kansas-city",
    "name": "Kansas City",
    "stateCode": "MO",
    "statewide": false,
    "lat": 39.0997,
    "lng": -94.5786,
    "radiusMiles": 75,
    "url": "/kansas-city-real-estate-agent.html"
  },
  {
    "slug": "washington-dc",
    "name": "Washington DC",
    "stateCode": "DC",
    "statewide": false,
    "lat": 38.9072,
    "lng": -77.0369,
    "radiusMiles": 75,
    "url": "/washington-dc-real-estate-agent.html"
  },
  {
    "slug": "virginia",
    "name": "Virginia",
    "stateCode": "VA",
    "statewide": true,
    "lat": 37.4316,
    "lng": -78.6569,
    "radiusMiles": 180,
    "url": "/virginia-real-estate-agent.html"
  },
  {
    "slug": "denver",
    "name": "Denver",
    "stateCode": "CO",
    "statewide": false,
    "lat": 39.7392,
    "lng": -104.9903,
    "radiusMiles": 75,
    "url": "/denver-real-estate-agent.html"
  },
  {
    "slug": "seattle",
    "name": "Seattle",
    "stateCode": "WA",
    "statewide": false,
    "lat": 47.6062,
    "lng": -122.3321,
    "radiusMiles": 75,
    "url": "/seattle-real-estate-agent.html"
  },
  {
    "slug": "tampa",
    "name": "Tampa",
    "stateCode": "FL",
    "statewide": false,
    "lat": 27.9506,
    "lng": -82.4572,
    "radiusMiles": 75,
    "url": "/tampa-real-estate-agent.html"
  },
  {
    "slug": "atlanta",
    "name": "Atlanta",
    "stateCode": "GA",
    "statewide": false,
    "lat": 33.749,
    "lng": -84.388,
    "radiusMiles": 75,
    "url": "/atlanta-real-estate-agent.html"
  },
  {
    "slug": "chicago",
    "name": "Chicago",
    "stateCode": "IL",
    "statewide": false,
    "lat": 41.8781,
    "lng": -87.6298,
    "radiusMiles": 75,
    "url": "/chicago-real-estate-agent.html"
  },
  {
    "slug": "portland",
    "name": "Portland",
    "stateCode": "OR",
    "statewide": false,
    "lat": 45.5152,
    "lng": -122.6784,
    "radiusMiles": 75,
    "url": "/portland-real-estate-agent.html"
  },
  {
    "slug": "phoenix",
    "name": "Phoenix",
    "stateCode": "AZ",
    "statewide": false,
    "lat": 33.4484,
    "lng": -112.074,
    "radiusMiles": 75,
    "url": "/phoenix-real-estate-agent.html"
  },
  {
    "slug": "las-vegas",
    "name": "Las Vegas",
    "stateCode": "NV",
    "statewide": false,
    "lat": 36.1699,
    "lng": -115.1398,
    "radiusMiles": 75,
    "url": "/las-vegas-real-estate-agent.html"
  },
  {
    "slug": "san-diego",
    "name": "San Diego",
    "stateCode": "CA",
    "statewide": false,
    "lat": 32.7157,
    "lng": -117.1611,
    "radiusMiles": 75,
    "url": "/san-diego-real-estate-agent.html"
  },
  {
    "slug": "salt-lake-city",
    "name": "Salt Lake City",
    "stateCode": "UT",
    "statewide": false,
    "lat": 40.7608,
    "lng": -111.891,
    "radiusMiles": 75,
    "url": "/salt-lake-city-real-estate-agent.html"
  },
  {
    "slug": "cincinnati",
    "name": "Cincinnati",
    "stateCode": "OH",
    "statewide": false,
    "lat": 39.1031,
    "lng": -84.512,
    "radiusMiles": 75,
    "url": "/cincinnati-real-estate-agent.html"
  },
  {
    "slug": "boston",
    "name": "Boston",
    "stateCode": "MA",
    "statewide": false,
    "lat": 42.3601,
    "lng": -71.0589,
    "radiusMiles": 75,
    "url": "/boston-real-estate-agent.html"
  },
  {
    "slug": "nashville",
    "name": "Nashville",
    "stateCode": "TN",
    "statewide": false,
    "lat": 36.1627,
    "lng": -86.7816,
    "radiusMiles": 75,
    "url": "/nashville-real-estate-agent.html"
  },
  {
    "slug": "louisville",
    "name": "Louisville",
    "stateCode": "KY",
    "statewide": false,
    "lat": 38.2527,
    "lng": -85.7585,
    "radiusMiles": 75,
    "url": "/louisville-real-estate-agent.html"
  },
  {
    "slug": "lexington",
    "name": "Lexington",
    "stateCode": "KY",
    "statewide": false,
    "lat": 38.0406,
    "lng": -84.5037,
    "radiusMiles": 75,
    "url": "/lexington-real-estate-agent.html"
  }
];
